# DSP391m - DATA SCIENCE CAPSTONE PROJECT
## PROGRESS REPORT 1: PROJECT PROPOSAL & MANAGEMENT PLAN

**Tên nhóm:** **DSP391m_G4 (Healthcare Analytics)**

### THÔNG TIN NHÓM & MỨC ĐỘ ĐÓNG GÓP (TEAM MEMBERS & CONTRIBUTIONS)

| STT | Họ và Tên | MSSV | Vai trò (Role) | Nhiệm vụ được giao (Assigned Tasks) | Mức độ đóng góp (%) |
|:---:|:---|:---|:---|:---|:---:|
| 1 | **Nguyễn Nhật Bằng** | HE190121 | Trưởng nhóm / Data Scientist | Khảo sát tài liệu, Xây dựng & Tinh chỉnh mô hình (Report 3), Đóng gói API (Report 4), Transpile sang C++ | 34% |
| 2 | **Đoàn Minh Tuấn** | HE190721 | Thành viên / Data Engineer | Thu thập dữ liệu IoT/Crawl data, Tiền xử lý & Khám phá dữ liệu EDA (Report 2), Quản lý Chiến lược dữ liệu | 33% |
| 3 | **Tạ Duy Anh** | HE190355 | Thành viên / Data Analyst | Trực quan hóa kết quả mô hình, Phân tích giá trị nghiệp vụ, Thiết kế Biểu đồ SHAP/ROC & Dashboard | 33% |

*(Lưu ý: Tổng mức độ đóng góp của toàn nhóm phải đạt 100%)*

**Giảng viên hướng dẫn:** Cao Văn Mai  
**Ngày nộp:** 25/05/2026

## 📌 DANH SÁCH ĐỀ TÀI GỢI Ý (SUGGESTED TOPICS)
*Sinh viên có thể lựa chọn 1 trong 7 hướng đề tài dưới đây hoặc đề xuất đề tài tương đương:*

### 1. Năng lượng & Phương tiện giao thông (Electric Vehicles & Transportation)
- **Dữ liệu:** US Electric Vehicle Charging Stations, VED Refined: 20M Engine Records, Global Petrol Prices.
- **Gợi ý ứng dụng:**
    - *Tối ưu hóa Ki-ốt sạc:* Dự báo nhu cầu sạc dựa trên biến động giá xăng dầu và tỷ lệ tiếp nhận xe điện.
    - *Bảo trì dự đoán (Predictive Maintenance):* Thuật toán phát hiện bất thường cho động cơ (ví dụ: Toyota Corolla Cross).

### 2. Giáo dục & Công nghệ theo dõi trẻ em (Education & Child Safety)
- **Dữ liệu:** Smartphone Usage & Addiction Analysis, Student Academic Performance.
- **Gợi ý ứng dụng:**
    - *Phân tích rủi ro thiết bị số:* Đánh giá tác động của nghiện smartphone lên sự tập trung, đồng bộ với dữ liệu Smartwatch.
    - *Khuyến nghị công thái học:* Gợi ý điều chỉnh môi trường học (bàn ghế, ánh sáng) dựa trên hiệu suất và thể chất trẻ.

### 3. Công nghệ IoT & Hệ thống nhúng (Technology & Edge Computing)
- **Dữ liệu:** Phishing Email Dataset, Telco Customer Churn Dataset.
- **Gợi ý ứng dụng:**
    - *Bảo mật lớp biên (Edge Security):* Huấn luyện TinyML phát hiện xâm nhập mạng, triển khai trực tiếp trên vi điều khiển như ESP32-C6.

### 4. Y tế & Chăm sóc sức khỏe (Healthcare) -- **[ĐỀ TÀI LỰA CHỌN]**
- **Dữ liệu:** MedInstruct-92K, Stroke Risk Dataset, Calorie Burn Efficiency.
- **Gợi ý ứng dụng:**
    - *Đánh giá rủi ro tim mạch:* Mô hình phân loại cảnh báo sớm đột quy dựa trên dữ liệu đốt calo và đặc trưng y tế.

### 5. Lĩnh vực Kinh tế (Economics & Finance)
- **Dữ liệu:** Global Commodity Prices, Inflation & CPI Datasets, Stock Market Tickers.
- **Gợi ý ứng dụng:**
    - *Dự báo hàng hóa & Năng lượng:* Phân tích tương quan địa chính trị với giá vàng/xăng dầu.
    - *Giao dịch định lượng (Quantitative Trading):* Phân tích tâm lý thị trường (Sentiment Analysis) từ tin tức tài chính.

### 6. Lĩnh vực Vũ trụ & Hàng không (Space & Aerospace)
- **Dữ liệu:** NASA Exoplanet Archive, Satellite Telemetry Data, Earth Observation Imagery.
- **Gợi ý ứng dụng:**
    - *Xử lý tín hiệu viễn thông vệ tinh:* Xây dựng bộ lọc tách nhiễu cho tín hiệu từ vệ tinh quỹ đạo thấp (LEO).
    - *Phân tích ảnh vệ tinh:* Sử dụng Computer Vision theo dõi biến đổi khí hậu hoặc sản lượng nông nghiệp.

### 7. Lĩnh vực Quân sự & An ninh quốc phòng (Military & Defense)
- **Dữ liệu:** Global Firepower Index, Radar & Sonar Signal Datasets, UAV Flight Logs.
- **Gợi ý ứng dụng:**
    - *Nhận diện mục tiêu bằng Radar/Sonar:* Phân loại phương tiện (UAV, máy bay dân dụng) trên thiết bị biên.
    - *Tối ưu hậu cần:* Thuật toán tối ưu tuyến đường tiếp tế trong điều kiện khắc nghiệt.

## I. TỔNG QUAN DỰ ÁN (PROJECT INTRODUCTION)

### 1.1. Đề tài lựa chọn
**Tên đề tài:** Tích hợp mô hình Học máy đa nguồn dữ liệu dự báo nguy cơ Đột quỵ với Ước lượng Tiêu hao Năng lượng nhân tạo (An Integrated Multi-Source Machine Learning Framework for Stroke Risk Prediction with Synthetic Energy Expenditure Estimation)

### 1.2. Lý do chọn đề tài & Động lực (Problem Statement & Motivation)
- Đột quỵ (Stroke) là một biến cố mạch máu não cực kỳ nguy hiểm, là nguyên nhân gây tử vong đứng thứ hai toàn cầu (chiếm khoảng 11% số ca tử vong) và là nguyên nhân chính dẫn đến tàn tật lâu dài ở người lớn. Phát hiện sớm đối tượng có nguy cơ cao giúp can thiệp kịp thời, cải thiện chất lượng sống và giảm chi phí y tế.
- Hiện nay, việc dự báo nguy cơ đột quỵ bằng học máy đối mặt với 2 thách thức lớn:
  1. **Rò rỉ dữ liệu (Data Leakage):** Nhiều bộ dữ liệu y tế chứa thông tin trùng lặp của cùng một bệnh nhân qua nhiều lần thăm khám (multi-visit). Việc phân tách dữ liệu ngẫu nhiên ở cấp độ dòng (row-level) khiến thông tin của cùng một bệnh nhân xuất hiện ở cả tập huấn luyện (train) và kiểm thử (test), tạo nên chỉ số chính xác giả tạo (artificially optimistic accuracy) nhưng hoạt động kém trên dữ liệu thực tế.
  2. **Thiếu hụt chỉ số hành vi (Behavioral Biomarkers):** Mức độ hoạt động thể chất và lượng năng lượng tiêu thụ (calories burned) là những chỉ báo quan trọng đối với nguy cơ tim mạch và đột quỵ. Tuy nhiên, các chỉ số này rất hiếm khi được ghi nhận trong các bệnh án điện tử (EHR) lâm sàng thông thường.
- **Động lực dự án:** Nhóm quyết định phát triển một framework học máy tích hợp kết nối hai tập dữ liệu (lâm sàng và thể chất). Dự án sử dụng giải pháp khử trùng lặp bệnh nhân để ngăn rò rỉ dữ liệu chéo, đồng thời xây dựng một mô hình hồi quy (XGBoost Regressor) để tạo đặc trưng calo tiêu thụ nhân tạo (`Estimated_calories`) từ tuổi, giới tính và BMI, làm giàu dữ liệu y tế để tối ưu hóa dự báo đột quỵ.

### 1.3. Mục tiêu & Phạm vi (Objectives & Scope)
- **Mục tiêu:**
  - Thiết lập một quy trình xử lý dữ liệu sạch, không rò rỉ thông tin bệnh nhân chéo thông qua thuật toán Deduplication.
  - Huấn luyện mô hình hồi quy ước lượng calo (`XGBRegressor`) đạt sai số tuyệt đối trung bình (MAE) thấp để tổng hợp đặc trưng hành vi.
  - So sánh 6 thuật toán học máy phân loại nguy cơ đột quỵ, tối ưu hóa ngưỡng quyết định F1-score trên tập validation để đạt chỉ số Recall tối ưu (tránh bỏ sót ca bệnh).
  - Phân tích đóng góp đặc trưng bằng SHAP để đảm bảo tính giải thích lâm sàng của mô hình.
  - Đóng gói toàn bộ mô hình và pipeline tiền xử lý thành mã nguồn C++ thuần túy (`stroke_predictor_model.h`) phục vụ triển khai thời gian thực trên các thiết bị nhúng biên lâm sàng.
- **Input/Output:**
  - **Đầu vào (Input):** Chỉ số lâm sàng bệnh nhân gồm Tuổi, Giới tính, Chỉ số khối cơ thể (BMI), Huyết áp (RestingBP), Cholesterol (heart_cholesterol), Mức đường huyết (avg_glucose_level), Tiền sử bệnh tim/huyết áp cao, Trạng thái hút thuốc.
  - **Đầu ra (Output):** Nhãn dự báo đột quỵ (0: Không có nguy cơ cao, 1: Có nguy cơ đột quỵ) và xác suất rủi ro đột quỵ chi tiết.

### 1.4. Đóng góp dự kiến
- **Đóng góp kỹ thuật:**
  - Giải quyết bài toán rò rỉ dữ liệu y tế bằng phương pháp gom cụm và khử trùng lặp cấp bệnh nhân (Patient-level Deduplication).
  - Phương pháp tổng hợp đặc trưng hành vi liên tập dữ liệu (Cross-dataset Feature Synthesis) bằng học máy.
  - Pipeline so sánh đa mô hình kết hợp tối ưu ngưỡng quyết định dưới điều kiện mất cân bằng nhãn nặng.
  - Giải pháp chuyển đổi mô hình (Transpilation) sang C++ thuần túy, mang lại tốc độ suy luận cực nhanh (<0.1 ms) và độc lập môi trường.
- **Đóng góp thực tiễn:**
  - Tạo ra công cụ hỗ trợ ra quyết định lâm sàng (Clinical Decision Support Tool) giúp sàng lọc đột quỵ sớm.
  - Khả năng tích hợp trực tiếp vào thiết bị biên hoặc phần mềm quản lý phòng khám không cần server Python.

## II. TỔNG QUAN TÀI LIỆU & CÔNG NGHỆ (RELATED WORKS & TECH STACK)

### 2.1. Các nghiên cứu liên quan (Literature Review)
Nhóm tiến hành khảo sát và phân tích 5 nguồn tài liệu tham khảo chính làm cơ sở lý thuyết cho dự án:
1. **Báo cáo Gánh nặng bệnh tật Đột quỵ Toàn cầu (Johnson et al., 2019):**
   - *Chi tiết tài liệu:* C.O. Johnson et al., "Global, regional, and national burden of stroke, 1990-2016: GBD Study 2016," *Lancet Neurology*, vol. 18, pp. 439-458, 2019.
   - *Ứng dụng:* Tài liệu cung cấp dữ liệu dịch tễ học vững chắc khẳng định đột quỵ là nguyên nhân gây tử vong thứ hai trên thế giới. Nghiên cứu nhấn mạnh tầm quan trọng của việc sàng lọc các yếu tố nguy cơ có thể kiểm soát được (như huyết áp, hoạt động thể chất) để ngăn ngừa đột quỵ.
2. **Thuật toán XGBoost (Chen & Guestrin, 2016):**
   - *Chi tiết tài liệu:* T. Chen and C. Guestrin, "XGBoost: A Scalable Tree Boosting System," *Proc. 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining*, 2016, pp. 785-794.
   - *Ứng dụng:* Công trình nghiên cứu nền tảng về thuật toán XGBoost. Phương pháp này cung cấp cơ chế kiểm soát overfitting thông qua chính quy hóa (L1/L2 regularization) và khả năng xử lý mất cân bằng nhãn dữ liệu y tế hiệu quả thông qua tham số `scale_pos_weight`, là lựa chọn hàng đầu cho mô hình dự báo của dự án.
3. **Phát hiện đột quỵ bằng các kỹ thuật học máy (Dritsas & Trigka, 2022):**
   - *Chi tiết tài liệu:* E. Dritsas and M. Trigka, "Stroke Risk Prediction with Machine Learning Techniques," *Sensors*, vol. 22, no. 13, p. 4670, 2022.
   - *Ứng dụng:* Các tác giả đã thực nghiệm so sánh nhiều mô hình học máy trên dữ liệu đột quỵ, chứng minh rằng các thuật toán Ensemble (như Random Forest, XGBoost) mang lại hiệu quả tốt hơn đáng kể so với các mô hình tuyến tính truyền thống. Đây là cơ sở để chúng tôi lựa chọn tập hợp các mô hình phân loại để so sánh.
4. **Giải thích mô hình học máy bằng SHAP (Lundberg & Lee, 2017):**
   - *Chi tiết tài liệu:* S.M. Lundberg and S.-I. Lee, "A Unified Approach to Interpreting Model Predictions," *Advances in Neural Information Processing Systems*, vol. 30, 2017.
   - *Ứng dụng:* Đề xuất phương pháp SHAP dựa trên lý thuyết trò chơi để giải thích đóng góp của từng đặc trưng đầu vào. Trong y khoa, tính giải thích là bắt buộc; SHAP giúp nhóm làm sáng tỏ cách mô hình đưa ra dự báo, đồng thời giúp phát hiện các đặc trưng có mối quan hệ phản khoa học (Red-flag features) để loại bỏ.
5. **Bài toán rò rỉ dữ liệu trong dự báo y khoa (Tran et al., 2020):**
   - *Chi tiết tài liệu:* T.T.K. Tran et al., "Improving Prediction of Ischemic Stroke Using Deep Learning," *Proceedings of the 5th International Conference on AICI*, 2020.
   - *Ứng dụng:* Tài liệu chỉ ra rằng việc sử dụng dữ liệu lâm sàng nhiều lượt khám (multi-visit) mà không xử lý trùng lặp sẽ dẫn đến rò rỉ dữ liệu nghiêm trọng khi phân chia ngẫu nhiên. Điều này thúc đẩy nhóm phát triển giải pháp patient-level deduplication làm sạch dữ liệu triệt để.

### 2.2. Tech Stack đề xuất
- **Ngôn ngữ lập trình:** Python 3.11+
- **Xử lý dữ liệu:**
  - `pandas`: Đọc, làm sạch, gom nhóm (deduplicate) và biến đổi dữ liệu dạng bảng.
  - `numpy`: Hỗ trợ tính toán số học nâng cao và xử lý mảng.
- **Học máy & Đánh giá:**
  - `scikit-learn`: Cung cấp các mô hình học máy cơ sở, chia tập dữ liệu (`train_test_split`), và các hàm đo lường chất lượng mô hình (F1, AUC-ROC, Accuracy).
  - `xgboost`: Xây dựng các mô hình hồi quy và phân loại tối ưu cao.
  - `joblib`: Đóng gói và lưu trữ mô hình đã huấn luyện.
- **Trực quan hóa:**
  - `matplotlib` & `seaborn`: Vẽ các phân phối dữ liệu, ma trận nhầm lẫn và đường cong ROC.
- **Giải thích mô hình:**
  - `shap`: Phân tích tác động và vai trò của các đặc trưng sinh học đối với dự báo đột quỵ.
- **Triển khai biên:**
  - C++17 và trình biên dịch `g++` để thực thi mã nguồn C++ thuần túy đã được transpile, đạt tốc độ suy luận tối đa.

## III. CHIẾN LƯỢC DỮ LIỆU (DATA STRATEGY)

### 3.1. Nguồn dữ liệu
Dự án sử dụng hai tập dữ liệu thô phục vụ cho việc liên kết và tổng hợp đặc trưng:
1. **Tập dữ liệu Đột quỵ lâm sàng (Stroke Clinical Dataset):**
   - *Đường dẫn:* `Stroke_dt/Stroke_dt.csv`
   - *Mô tả:* Chứa dữ liệu của bệnh nhân khám lâm sàng với 143,960 dòng dữ liệu ban đầu và 26 cột thuộc tính (bao gồm các chỉ số sinh lý như tuổi, BMI, đường huyết, huyết áp, chẩn đoán bệnh tim, tình trạng hút thuốc, và nhãn mục tiêu `stroke_target`).
   - *Đặc điểm:* Dữ liệu bị trùng lặp nhiều bản ghi trên cùng một bệnh nhân (nhiều lượt khám) và nhãn đột quỵ bị mất cân bằng nặng (chỉ khoảng 4.87% bệnh nhân thực sự bị đột quỵ).
2. **Tập dữ liệu Tiêu hao năng lượng (Calories Burn Dataset):**
   - *Đường dẫn:* `Calo_burn/calories.csv`
   - *Mô tả:* Ghi lại thông tin tập luyện của 15,000 cá nhân gồm Giới tính, Tuổi, Chiều cao, Cân nặng, và lượng calo tiêu thụ thực tế (`Calories`).
   - *Mục đích:* Tập dữ liệu này được dùng độc lập để huấn luyện mô hình hồi quy XGBoost ước lượng năng lượng tiêu thụ, từ đó ánh xạ sang tập dữ liệu đột quỵ làm đặc trưng hành vi.

### 3.2. Demo Ingestion & Inspection
Đoạn mã dưới đây thực hiện việc nạp thử dữ liệu từ hai tệp tin CSV, kiểm tra cấu trúc cơ bản và in ra các thống kê mô tả ban đầu để kiểm định chất lượng dữ liệu trước khi tiến hành các bước tiền xử lý chuyên sâu.

In [1]:
# Code cell: Load dữ liệu và hiển thị thông tin cơ bản (head, info, describe)
import pandas as pd
import os

# 1. Đọc dữ liệu đột quỵ lâm sàng (Stroke Clinical Dataset)
stroke_path = "Stroke_dt/Stroke_dt.csv"
if os.path.exists(stroke_path):
    df_stroke = pd.read_csv(stroke_path)
    print("=== TẬP DỮ LIỆU ĐỘT QUỲ LÂM SÀNG ===")
    print(f"Kích thước dữ liệu: {df_stroke.shape[0]} dòng, {df_stroke.shape[1]} cột\n")
    print("5 dòng dữ liệu đầu tiên:")
    display(df_stroke.head())
    print("\nCấu trúc các cột dữ liệu:")
    df_stroke.info()
    print("\nThống kê mô tả dữ liệu:")
    display(df_stroke.describe())
else:
    print(f"Lỗi: Không tìm thấy file dữ liệu đột quỵ tại {stroke_path}")

print("\n" + "="*50 + "\n")

# 2. Đọc dữ liệu tiêu hao năng lượng (Calories Burn Dataset)
calories_path = "Calo_burn/calories.csv"
if os.path.exists(calories_path):
    df_calories = pd.read_csv(calories_path)
    print("=== TẬP DỮ LIỆU TIÊU HAO NĂNG LƯỢNG (CALORIES) ===")
    print(f"Kích thước dữ liệu: {df_calories.shape[0]} dòng, {df_calories.shape[1]} cột\n")
    print("5 dòng dữ liệu đầu tiên:")
    display(df_calories.head())
    print("\nCấu trúc các cột dữ liệu:")
    df_calories.info()
    print("\nThống kê mô tả dữ liệu:")
    display(df_calories.describe())
else:
    print(f"Lỗi: Không tìm thấy file dữ liệu Calo tại {calories_path}")

=== TẬP DỮ LIỆU ĐỘT QUỲ LÂM SÀNG ===
Kích thước dữ liệu: 143960 dòng, 26 cột

5 dòng dữ liệu đầu tiên:

,patient_id,age,hypertension,heart_disease,avg_glucose_level,bmi,avg_RestingBP,heart_cholesterol,avg_MaxHR,avg_Oldpeak,...,cardio_gluc,cardio_rate,stroke_target,gender,ever_married,work_type,Residence_type,smoking_status,smoke_flag,alco_flag
0,55235,50,0,0,85.92,37.3,125.714286,219.285714,140.571429,0.528571,...,1.0,0.0,0,Female,Yes,Self-employed,Urban,smokes,0,0
1,55235,50,0,0,85.92,37.3,125.714286,219.285714,140.571429,0.528571,...,1.0,0.0,0,Female,Yes,Self-employed,Urban,smokes,0,0
2,55235,50,0,0,85.92,37.3,125.714286,219.285714,140.571429,0.528571,...,1.0,0.0,0,Female,Yes,Self-employed,Urban,smokes,0,0
3,55235,50,0,0,85.92,37.3,125.714286,219.285714,140.571429,0.528571,...,1.0,0.0,0,Female,Yes,Self-employed,Urban,smokes,0,0
4,55235,50,0,0,85.92,37.3,125.714286,219.285714,140.571429,0.528571,...,1.0,0.0,0,Female,Yes,Self-employed,Urban,smokes,0,0

Cấu trúc các cột dữ liệu:
<class 'pandas.DataFrame'>
RangeIndex: 143960 entries, 0 to 143959
Data columns (total 26 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   patient_id          143960 non-null  int64
 1   age                 143960 non-null  int64
 2   hypertension        143960 non-null  int64
 3   heart_disease       143960 non-null  int64
 4   avg_glucose_level   143960 non-null  float64
 5   bmi                 143960 non-null  float64
 6   avg_RestingBP       127608 non-null  float64
 7   heart_cholesterol   127608 non-null  float64
 8   avg_MaxHR           127608 non-null  float64
 9   avg_Oldpeak         127608 non-null  float64
 10  heart_disease_rate  127608 non-null  float64
 11  avg_height          112288 non-null  float64
 12  avg_weight          112288 non-null  float64
 13  avg_ap_hi           112288 non-null  float64
 14  avg_ap_lo           112288 non-null  float64
 15  cardio_cholesterol  112288 non-null  float64
 16  cardio_gluc         112288 non-null  float64
 17  cardio_rate         112288 non-null  float64
 18  stroke_target       143960 non-null  int64
 19  gender              143952 non-null  str
 20  ever_married        143960 non-null  str
 21  work_type           143960 non-null  str
 22  Residence_type      143960 non-null  str
 23  smoking_status      143960 non-null  str
 24  smoke_flag          143960 non-null  int64
 25  alco_flag           143960 non-null  int64
dtypes: float64(14), int64(7), str(5)
memory usage: 28.6 MB

Thống kê mô tả dữ liệu:

,patient_id,age,hypertension,heart_disease,avg_glucose_level,bmi,avg_RestingBP,heart_cholesterol,avg_MaxHR,avg_Oldpeak,...,avg_height,avg_weight,avg_ap_hi,avg_ap_lo,cardio_cholesterol,cardio_gluc,cardio_rate,stroke_target,smoke_flag,alco_flag
count,143960.00000,143960.000000,143960.000000,143960.000000,143960.000000,143960.000000,127608.000000,127608.000000,127608.000000,127608.000000,...,112288.000000,112288.000000,112288.000000,112288.000000,112288.000000,112288.000000,112288.000000,143960.000000,143960.000000,143960.000000
mean,36778.98344,50.501417,0.133093,0.054237,110.651298,29.488608,132.254728,218.477437,139.986399,0.826996,...,165.464947,73.118552,126.616130,96.746936,1.052152,1.049872,0.019664,0.046457,0.084690,0.053570
std,21224.58745,13.994631,0.339676,0.226486,48.788801,9.752226,7.974760,45.382351,11.108760,0.455768,...,5.393463,7.259281,8.927519,50.449913,0.248941,0.262762,0.138842,0.210474,0.278421,0.225169
min,67.00000,0.000000,0.000000,0.000000,55.120000,0.000000,100.000000,0.000000,110.666667,0.000000,...,154.000000,60.000000,110.000000,40.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,18181.00000,46.000000,0.000000,0.000000,78.180000,25.400000,128.750000,197.645161,132.703704,0.373333,...,161.000000,68.312500,120.000000,77.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,37440.00000,54.000000,0.000000,0.000000,93.960000,29.600000,132.242424,216.600000,140.571429,0.883333,...,163.000000,71.625000,123.000000,80.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,55244.00000,58.000000,0.000000,0.000000,121.110000,34.600000,135.370370,243.166667,147.200000,1.041667,...,170.000000,75.714286,130.000000,86.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,72940.00000,82.000000,1.000000,1.000000,271.740000,97.600000,170.000000,392.000000,191.000000,3.500000,...,176.000000,93.000000,150.000000,386.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

==================================================

=== TẬP DỮ LIỆU TIÊU HAO NĂNG LƯỢNG (CALORIES) ===
Kích thước dữ liệu: 15000 dòng, 9 cột

5 dòng dữ liệu đầu tiên:

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0

Cấu trúc các cột dữ liệu:
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_ID     15000 non-null  int64
 1   Gender      15000 non-null  str
 2   Age         15000 non-null  int64
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
 8   Calories    15000 non-null  float64
dtypes: float64(6), int64(2), str(1)
memory usage: 1.0 MB

Thống kê mô tả dữ liệu:

,User_ID,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
count,1.500000e+04,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,1.497736e+07,42.789800,174.465133,74.966867,15.530600,95.518533,40.025453,89.539533
std,2.872851e+06,16.980264,14.258114,15.035657,8.319203,9.583328,0.779230,62.456978
min,1.000116e+07,20.000000,123.000000,36.000000,1.000000,67.000000,37.100000,1.000000
25%,1.247419e+07,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,35.000000
50%,1.499728e+07,39.000000,175.000000,74.000000,16.000000,96.000000,40.200000,79.000000
75%,1.744928e+07,56.000000,185.000000,87.000000,23.000000,103.000000,40.600000,138.000000
max,1.999965e+07,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000

## IV. KẾ HOẠCH QUẢN LÝ DỰ ÁN (PROJECT MANAGEMENT PLAN)

### 4.1. Task Management

| Task Name | Priority | Owner | Start date | End date | Status | Issues |
|:---|:---|:---|:---|:---|:---|:---|
| **Report 1: Project Proposal & Management** | High | Cả nhóm | 15/05/2026 | 25/05/2026 | **Done** | Không có |
| **Data Collection & Cleaning (Deduplication)**| High | Đoàn Minh Tuấn | 26/05/2026 | 02/06/2026 | **In Progress** | Phát hiện trùng lặp nhiều bản ghi/bệnh nhân |
| **Report 2: Exploratory Data Analysis (EDA)** | High | Đoàn Minh Tuấn, Tạ Duy Anh | 03/06/2026 | 15/06/2026 | **To Do** | Trực quan hóa tương quan phân phối các biến |
| **Stage 1: Calories Regressor Model (XGB)** | Medium | Nguyễn Nhật Bằng | 16/06/2026 | 25/06/2026 | **To Do** | Imputation các giá trị BMI ngoài sinh học |
| **Stage 2: Stroke Risk Model Training (Report 3)**| High | Nguyễn Nhật Bằng | 26/06/2026 | 10/07/2026 | **To Do** | Xử lý mất cân bằng nhãn nặng (4.87% positive) |
| **Feature Diagnostics (SHAP Interpretation)** | Medium | Tạ Duy Anh | 11/07/2026 | 20/07/2026 | **To Do** | Phát hiện và loại bỏ các đặc trưng "Red-flag" |
| **Report 4: Model Transpilation & C++ API** | High | Nguyễn Nhật Bằng | 21/07/2026 | 30/07/2026 | **To Do** | Đảm bảo độ sai khác xác suất suy luận < 1e-4 |
| **Final Evaluation & Slides/Dashboard** | High | Tạ Duy Anh, Cả nhóm | 01/08/2026 | 05/08/2026 | **To Do** | Chuẩn bị báo cáo trước hội nghị BIOXPLORE 2026 |

### 4.2. Risk Management

| Risk Description | Impact | Possibility | Response Plans |
|:---|:---:|:---:|:---|
| **Rò rỉ thông tin bệnh nhân (Data Leakage)** | Cao | Cao | Áp dụng quy trình khử trùng lặp cấp bệnh nhân (Patient-level Deduplication) trước khi thực hiện phân chia dữ liệu Train/Validation/Test. |
| **Mất cân bằng nhãn đột quỵ cực kỳ nặng** | Cao | Cao | Sử dụng trọng số lớp (`scale_pos_weight` / `class_weight='balanced'`) và tối ưu hóa ngưỡng quyết định F1-score trên tập Validation thay vì dùng ngưỡng mặc định 0.5. |
| **Các tính năng có tương quan sinh lý học nghịch đảo (Red-flags)** | Cao | Trung bình | Kiểm tra tương quan Pearson/Spearman và chiều tác động SHAP. Loại bỏ các tính năng gây nhiễu và đi ngược lại lâm sàng thực tế (như huyết áp cao lại làm giảm nguy cơ đột quỵ). |
| **Sai lệch dự đoán khi biên dịch mô hình sang C++** | Trung bình | Thấp | Thực hiện kiểm tra so sánh tự động (ONNX Runtime & C++ vs Python output) trên một mẫu lớn dữ liệu kiểm thử để bảo đảm sai số suy luận tiệm cận 0. |
| **Collinearity giữa BMI, Cân nặng và Chiều cao** | Trung bình | Cao | Loại bỏ cân nặng và chiều cao khỏi tập đặc trưng phân loại chính. Sử dụng lượng calo tiêu thụ ước tính (`Estimated_calories`) làm đặc trưng thay thế để biểu diễn thể trạng vật lý. |